In [1]:
import pandas as pd

In [3]:
data_df = pd.read_csv('tool.csv')
data_df

,Unnamed: 0,Listing,Actions,Avg Sold Price,Avg Shipping,Total Sold,Item_Sale,Bids,Date Last Sold
0,0,", preview full size imageStanley mechanics han...",EditSell SimilarExclude listing,$131.99Fixed price,$0.00100% Free shipping,8,"$1,055.92",–,"Mar 19, 2024"
1,1,", preview full size image8 Pcs Stanley, Plomb ...",EditSell SimilarExclude listing,$23.97Fixed price,$0.00100% Free shipping,1,$23.97,–,"Mar 19, 2024"
2,2,", preview full size imageCommercial Electric E...",EditSell SimilarExclude listing,$64.00Fixed price,$0.00100% Free shipping,1,$64.00,–,"Mar 19, 2024"
3,3,", preview full size imageVCT Tool 399pc Piece ...",EditSell SimilarExclude listing,$26.06Fixed price,$50.6097% Free shipping,108,"$2,814.60",–,"Mar 19, 2024"
4,4,", preview full size image205 PCS Tool Set Mech...",EditSell SimilarExclude listing,$70.23Fixed price,$0.00100% Free shipping,177,"$12,430.23",–,"Mar 19, 2024"
...,...,...,...,...,...,...,...,...,...
4195,45,", preview full size imageCartman 148-Piece Too...",EditExclude listing,$29.95Fixed price,$0.00100% Free shipping,1,$29.95,–,"Jan 3, 2022"
4196,46,", preview full size image799 PCS Hand Tool Set...",EditExclude listing,$155.55Fixed price,$0.00100% Free shipping,1,$155.55,–,"Jan 3, 2022"
4197,47,", preview full size imageDOWELL 10 Piece Small...",EditExclude listing,$33.68Fixed price,$0.00100% Free shipping,2,$67.35,–,"Jan 3, 2022"
4198,48,", preview full size image128PCS Hand Tool Set ...",EditExclude listing,$51.29Fixed price,$0.00100% Free shipping,1,$51.29,–,"Jan 2, 2022"
4199,49,", preview full size image900pcs M3-M10 Hand Ri...",EditExclude listing,$80.71Fixed price,$0.00100% Free shipping,3,$242.13,–,"Jan 2, 2022"

In [4]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag

# Download NLTK resources (only need to do this once)
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# Function to extract keywords
def extract_keywords(text):
    tokens = word_tokenize(text)
    tagged_tokens = pos_tag(tokens)
    keywords = [word for word, pos in tagged_tokens if pos in ['NN', 'NNS', 'NNP', 'JJ']]
    return keywords

[nltk_data] Downloading package punkt to /Users/evanbruno/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/evanbruno/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [5]:


# Function to extract and format the first part of the string
def extract_and_format(value):
    parts = value.split('%')[0].split('$')[1]
    first_part = parts.strip()
    formatted_value = '{:.2f}'.format(float(first_part[1:]))
    return formatted_value
# Remove commas from all values in the DataFrame
data_df = data_df.replace(',', '', regex=True)
# 
data_df['Avg_Sold_Price'] = data_df['Avg Sold Price'].apply(lambda x: x.split('$')[1].split('F')[0].split('A')[0]).astype(float)

# 
data_df['Total_Sales'] = data_df['Item_Sale'].apply(lambda x: x.split('$')[1]).astype(float)

data_df['Total_Sold'] = data_df['Total Sold'].astype(float)

# Convert string to datetime
data_df['Date'] = pd.to_datetime(data_df['Date Last Sold'])

# Apply the function to the column
data_df['Shipping'] = data_df['Avg Shipping'].apply(lambda x: extract_and_format(x)).astype(float)

data_df.drop(columns=['Unnamed: 0', 'Actions', 'Avg Sold Price', 'Bids', 'Date Last Sold', 'Avg Shipping', 'Item_Sale', 'Total Sold'], inplace=True)

data_df['Listing'] = data_df['Listing'].apply(lambda x: x.split('image')[-1])

# Apply the function to both listing titles and descriptions
data_df['Title_Keywords'] = data_df['Listing'].apply(extract_keywords)

data_df

,Listing,Avg_Sold_Price,Total_Sales,Total_Sold,Date,Shipping,Title_Keywords
0,Stanley mechanics hand tool set 201-piece with...,131.99,1055.92,8.0,2024-03-19,0.00,"[Stanley, mechanics, hand, tool, 201-piece, po..."
1,8 Pcs Stanley Plomb and Assorted Workshop Equi...,23.97,23.97,1.0,2024-03-19,0.00,"[Pcs, Stanley, Plomb, Assorted, Workshop, Equi..."
2,Commercial Electric Electrical Hand Tool Set 2...,64.00,64.00,1.0,2024-03-19,0.00,"[Commercial, Electric, Electrical, Hand, Tool,..."
3,VCT Tool 399pc Piece Multi-Use Electrical Repa...,26.06,2814.60,108.0,2024-03-19,0.61,"[VCT, Tool, Piece, Multi-Use, Electrical, Repa..."
4,205 PCS Tool Set Mechanics Tool Kit Wrenches S...,70.23,12430.23,177.0,2024-03-19,0.00,"[PCS, Tool, Set, Mechanics, Tool, Kit, Wrenche..."
...,...,...,...,...,...,...,...
4195,Cartman 148-Piece Tool Set - General Household...,29.95,29.95,1.0,2022-01-03,0.00,"[Cartman, 148-Piece, Tool, Set, General, House..."
4196,799 PCS Hand Tool Set Mechanics Kit Wrench Soc...,155.55,155.55,1.0,2022-01-03,0.00,"[PCS, Hand, Tool, Set, Mechanics, Kit, Wrench,..."
4197,DOWELL 10 Piece Small Tool KitMini Portable To...,33.68,67.35,2.0,2022-01-03,0.00,"[DOWELL, Piece, Small, Tool, KitMini, Portable..."
4198,128PCS Hand Tool Set Craftsman Hand Tool Set H...,51.29,51.29,1.0,2022-01-02,0.00,"[Hand, Tool, Set, Craftsman, Hand, Tool, Set, ..."
4199,900pcs M3-M10 Hand Riveter Rivnut Nut Insert N...,80.71,242.13,3.0,2022-01-02,0.00,"[M3-M10, Hand, Riveter, Rivnut, Nut, Insert, N..."

In [6]:
data_df['Month_Year'] = data_df['Date'].dt.strftime('%B %Y')

# Popular Whole DF

In [7]:
filtered_df= data_df.loc[data_df['Avg_Sold_Price'] > 10]
filtered_df

,Listing,Avg_Sold_Price,Total_Sales,Total_Sold,Date,Shipping,Title_Keywords,Month_Year
0,Stanley mechanics hand tool set 201-piece with...,131.99,1055.92,8.0,2024-03-19,0.00,"[Stanley, mechanics, hand, tool, 201-piece, po...",March 2024
1,8 Pcs Stanley Plomb and Assorted Workshop Equi...,23.97,23.97,1.0,2024-03-19,0.00,"[Pcs, Stanley, Plomb, Assorted, Workshop, Equi...",March 2024
2,Commercial Electric Electrical Hand Tool Set 2...,64.00,64.00,1.0,2024-03-19,0.00,"[Commercial, Electric, Electrical, Hand, Tool,...",March 2024
3,VCT Tool 399pc Piece Multi-Use Electrical Repa...,26.06,2814.60,108.0,2024-03-19,0.61,"[VCT, Tool, Piece, Multi-Use, Electrical, Repa...",March 2024
4,205 PCS Tool Set Mechanics Tool Kit Wrenches S...,70.23,12430.23,177.0,2024-03-19,0.00,"[PCS, Tool, Set, Mechanics, Tool, Kit, Wrenche...",March 2024
...,...,...,...,...,...,...,...,...
4195,Cartman 148-Piece Tool Set - General Household...,29.95,29.95,1.0,2022-01-03,0.00,"[Cartman, 148-Piece, Tool, Set, General, House...",January 2022
4196,799 PCS Hand Tool Set Mechanics Kit Wrench Soc...,155.55,155.55,1.0,2022-01-03,0.00,"[PCS, Hand, Tool, Set, Mechanics, Kit, Wrench,...",January 2022
4197,DOWELL 10 Piece Small Tool KitMini Portable To...,33.68,67.35,2.0,2022-01-03,0.00,"[DOWELL, Piece, Small, Tool, KitMini, Portable...",January 2022
4198,128PCS Hand Tool Set Craftsman Hand Tool Set H...,51.29,51.29,1.0,2022-01-02,0.00,"[Hand, Tool, Set, Craftsman, Hand, Tool, Set, ...",January 2022
4199,900pcs M3-M10 Hand Riveter Rivnut Nut Insert N...,80.71,242.13,3.0,2022-01-02,0.00,"[M3-M10, Hand, Riveter, Rivnut, Nut, Insert, N...",January 2022

In [8]:
from collections import Counter

In [9]:

def extract_phrases(title):
    tokens = title.split()  # Tokenize the title
    phrases = []
    for i in range(len(tokens)):
        for j in range(i + 1, min(i + 6, len(tokens) + 1)):  # Generate combinations of 2 to 5 words
            phrase = ' '.join(tokens[i:j])
            if len(phrase.split()) >= 2 and len(phrase.split()) <= 5:  # Check if phrase length is between 2 and 5
                phrases.append(phrase)
    return phrases

# Apply the function to the Titles column
phrases = filtered_df['Listing'].apply(extract_phrases).sum()

# Count the occurrences of each phrase
phrase_counts = Counter(phrases)

# Find the most common phrases
most_common_phrases = phrase_counts.most_common()

most_common_phrases_df = pd.DataFrame(most_common_phrases, columns=['Name', 'Count'])
most_common_phrases_df.head(25)

                               Name  Count
0                         Hand Tool   3869
1                          Tool Set   3281
2                          Tool Kit   1980
3                     Hand Tool Set   1705
4                        Hand Tools   1346
5                     Hand Tool Kit   1192
6                    Household Hand   1187
7               Household Hand Tool   1016
8                 General Household    757
9            General Household Hand    686
10          Household Hand Tool Kit    662
11      General Household Hand Tool    624
12                   Milwaukee Hand    608
13                         Kit with    602
14                      Home Repair    554
15                    Tool Kit with    530
16                      Repair Tool    524
17                      Set General    508
18  General Household Hand Tool Kit    506
19                 Tool Set General    497
20               Hand Tool Kit with    464
21                   Mechanics Tool    458
22                           Lot Of    454
23            Set General Household    424
24                    Set Mechanics    418

In [10]:
type_product = most_common_phrases_df['Name'].head(100).tolist()

In [11]:

dict_sales = {'Phrase': [], 'Avg_Sold_Price_mean': [], 'Avg_Sold_Price_25': [], 'Avg_Sold_Price_75': [], 'Total_Sold': [], 'Ship_Cost': [], 'Count_Unique': []}


for phrase in type_product:
    # Filter rows where 'filtered_df' or 'Vitamin' is in the list
    temp_df = filtered_df[filtered_df['Listing'].apply(lambda x: phrase in x)]

    mean = temp_df.describe()['Avg_Sold_Price'].tolist()[1]

    percent_25 = temp_df.describe()['Avg_Sold_Price'].tolist()[4]

    percent_75 = temp_df.describe()['Avg_Sold_Price'].tolist()[6]

    total = temp_df['Total_Sold'].sum()

    ship = temp_df.describe()['Shipping'].tolist()[5]
    
    count =  temp_df.describe()['Total_Sold'].tolist()[0]
    
    dict_sales['Phrase'].append(phrase)
    dict_sales['Avg_Sold_Price_mean'].append(mean)
    dict_sales['Avg_Sold_Price_25'].append(percent_25)
    dict_sales['Avg_Sold_Price_75'].append(percent_75)
    dict_sales['Total_Sold'].append(total)
    dict_sales['Ship_Cost'].append(ship)
    dict_sales['Count_Unique'].append(count)
    
stats_df = pd.DataFrame.from_dict(dict_sales)

stats_df['Ratio_Sold_Count'] = stats_df['Total_Sold'] / stats_df['Count_Unique']

In [12]:
stats_df.sort_values(by='Avg_Sold_Price_mean', ascending=False).head(10)

,Phrase,Avg_Sold_Price_mean,Avg_Sold_Price_25,Avg_Sold_Price_75,Total_Sold,Ship_Cost,Count_Unique,Ratio_Sold_Count
59,Mechanics Hand Tool Set,250.867823,87.1000,189.9900,396.0,0.0,124.0,3.193548
48,Mechanics Hand Tool,222.810196,78.7000,189.9900,448.0,0.0,153.0,2.928105
38,Mechanics Hand,216.637702,70.0000,189.9900,469.0,0.0,161.0,2.913043
56,Mechanics Tool Set,114.731940,56.9625,157.7900,710.0,0.0,134.0,5.298507
75,Set -,90.761262,19.1500,39.2250,492.0,0.0,103.0,4.776699
21,Mechanics Tool,89.680373,36.9900,100.0000,2293.0,0.0,241.0,9.514523
3,Hand Tool Set,86.756557,31.3650,81.0225,7798.0,0.0,944.0,8.260593
83,Tool Set -,85.210957,19.4700,38.9900,481.0,0.0,94.0,5.117021
72,Milwaukee Hand Tools-,80.591154,59.9900,89.9900,130.0,0.0,130.0,1.000000
46,Hand Tools-,79.741061,59.9900,89.9900,198.0,0.0,198.0,1.000000

In [13]:
stats_df.sort_values(by='Total_Sold', ascending=False).head(10)

,Phrase,Avg_Sold_Price_mean,Avg_Sold_Price_25,Avg_Sold_Price_75,Total_Sold,Ship_Cost,Count_Unique,Ratio_Sold_Count
0,Hand Tool,71.662616,29.9500,76.2600,14481.0,0.0,2928.0,4.945697
1,Tool Set,73.721610,29.6750,73.9400,12336.0,0.0,1739.0,7.093732
3,Hand Tool Set,86.756557,31.3650,81.0225,7798.0,0.0,944.0,8.260593
2,Tool Kit,61.308917,29.6225,64.4600,6806.0,0.0,1062.0,6.408663
24,Set Mechanics,55.032118,29.9900,70.1100,4374.0,0.0,203.0,21.546798
26,Tool Set Mechanics,55.391616,29.9900,70.8000,4345.0,0.0,198.0,21.944444
27,Mechanics Kit,51.888952,29.9900,63.4900,4135.0,0.0,210.0,19.690476
30,Hand Tool Set Mechanics,55.535211,29.9900,71.4100,4121.0,0.0,190.0,21.689474
5,Hand Tool Kit,64.443414,27.5900,63.3600,4075.0,0.0,665.0,6.127820
6,Household Hand,43.989317,26.0375,53.9900,3916.0,0.0,600.0,6.526667

In [14]:
stats_df.sort_values(by='Ratio_Sold_Count', ascending=False).head(10)

,Phrase,Avg_Sold_Price_mean,Avg_Sold_Price_25,Avg_Sold_Price_75,Total_Sold,Ship_Cost,Count_Unique,Ratio_Sold_Count
95,PCS Hand Tool,66.675514,39.990,85.8350,3334.0,0.0,107.0,31.158879
92,PCS Hand,65.938257,39.990,85.6800,3336.0,0.0,109.0,30.605505
78,Kit Wrench,62.220526,32.340,85.6750,3376.0,0.0,114.0,29.614035
71,Wrench Socket,59.821028,31.640,78.9150,3115.0,0.0,107.0,29.112150
44,Hand Tool Set Mechanics Kit,53.197397,29.990,65.2775,3372.0,0.0,146.0,23.095890
40,Tool Set Mechanics Kit,52.981409,29.990,65.0000,3407.0,0.0,149.0,22.865772
39,Set Mechanics Kit,52.711060,29.985,64.5550,3411.0,0.0,151.0,22.589404
26,Tool Set Mechanics,55.391616,29.990,70.8000,4345.0,0.0,198.0,21.944444
30,Hand Tool Set Mechanics,55.535211,29.990,71.4100,4121.0,0.0,190.0,21.689474
24,Set Mechanics,55.032118,29.990,70.1100,4374.0,0.0,203.0,21.546798