In [8]:
import pandas as pd

In [9]:
data_df = pd.read_csv('lubricant.csv')
data_df

,Unnamed: 0,Listing,Actions,Avg Sold Price,Avg Shipping,Total Sold,Item_Sale,Bids,Date Last Sold
0,0,", preview full size image10oz Lubricant Semen ...",EditSell SimilarExclude listing,$12.55Fixed price,$0.00100% Free shipping,82,"$1,029.34",–,"Mar 21, 2024"
1,1,", preview full size imagePersonal Lubricant Or...",EditSell SimilarExclude listing,$7.97Fixed price,$0.00100% Free shipping,19,$151.49,–,"Mar 21, 2024"
2,2,", preview full size imageNew Pjur Original Bod...",EditSell SimilarExclude listing,$114.00Fixed price,$0.00100% Free shipping,9,"$1,026.00",–,"Mar 21, 2024"
3,3,", preview full size imageEquate Liquid Persona...",EditSell SimilarExclude listing,$7.94Fixed price,$0.00100% Free shipping,12,$95.23,–,"Mar 21, 2024"
4,4,", preview full size imageK-Y Warming Liquid Pe...",EditSell SimilarExclude listing,$9.99Fixed price,$4.990% Free shipping,2,$19.98,–,"Mar 21, 2024"
...,...,...,...,...,...,...,...,...,...
9995,45,", preview full size imageFemale Increase Orgas...",EditExclude listing,$14.03Fixed price,$0.00100% Free shipping,49,$687.58,–,"Nov 3, 2023"
9996,46,", preview full size imageK-Y Jelly Personal Lu...",EditSell SimilarExclude listing,$18.80Fixed price,$0.00100% Free shipping,2,$37.60,–,"Nov 3, 2023"
9997,47,", preview full size imageConceive Fertility Fr...",EditExclude listing,$19.99Fixed price,$7.600% Free shipping,9,$179.91,–,"Nov 3, 2023"
9998,48,", preview full size imageHello Cake Tingle To ...",EditExclude listing,$12.69Fixed price,$0.00100% Free shipping,1,$12.69,–,"Nov 3, 2023"
9999,49,", preview full size imagePjur Original Concent...",EditExclude listing,$21.11Fixed price,$0.00100% Free shipping,5,$105.55,–,"Nov 3, 2023"

In [5]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag

# Download NLTK resources (only need to do this once)
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# Function to extract keywords
def extract_keywords(text):
    tokens = word_tokenize(text)
    tagged_tokens = pos_tag(tokens)
    keywords = [word for word, pos in tagged_tokens if pos in ['NN', 'NNS', 'NNP', 'JJ']]
    return keywords

[nltk_data] Downloading package punkt to /Users/evanbruno/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/evanbruno/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [10]:


# Function to extract and format the first part of the string
def extract_and_format(value):
    parts = value.split('%')[0].split('$')[1]
    first_part = parts.strip()
    formatted_value = '{:.2f}'.format(float(first_part[1:]))
    return formatted_value
# Remove commas from all values in the DataFrame
data_df = data_df.replace(',', '', regex=True)
# 
data_df['Avg_Sold_Price'] = data_df['Avg Sold Price'].apply(lambda x: x.split('$')[1].split('F')[0].split('A')[0]).astype(float)

# 
data_df['Total_Sales'] = data_df['Item_Sale'].apply(lambda x: x.split('$')[1]).astype(float)

data_df['Total_Sold'] = data_df['Total Sold'].astype(float)

# Convert string to datetime
data_df['Date'] = pd.to_datetime(data_df['Date Last Sold'])

# Apply the function to the column
data_df['Shipping'] = data_df['Avg Shipping'].apply(lambda x: extract_and_format(x)).astype(float)

data_df.drop(columns=['Unnamed: 0', 'Actions', 'Avg Sold Price', 'Bids', 'Date Last Sold', 'Avg Shipping', 'Item_Sale', 'Total Sold'], inplace=True)

data_df['Listing'] = data_df['Listing'].apply(lambda x: x.split('image')[-1])

# Apply the function to both listing titles and descriptions
data_df['Title_Keywords'] = data_df['Listing'].apply(extract_keywords)

data_df

,Listing,Avg_Sold_Price,Total_Sales,Total_Sold,Date,Shipping,Title_Keywords
0,10oz Lubricant Semen Long Lasting Water Based ...,12.55,1029.34,82.0,2024-03-21,0.00,"[Lubricant, Semen, Long, Lasting, Water, Sex, ..."
1,Personal Lubricant Organic Water Based Lube fo...,7.97,151.49,19.0,2024-03-21,0.00,"[Personal, Lubricant, Organic, Water, Lube, Wo..."
2,New Pjur Original Bodyglide Silky Silicone Lub...,114.00,1026.00,9.0,2024-03-21,0.00,"[New, Pjur, Original, Bodyglide, Silky, Silico..."
3,Equate Liquid Personal Lubricant Jelly Fragran...,7.94,95.23,12.0,2024-03-21,0.00,"[Equate, Liquid, Personal, Lubricant, Jelly, F..."
4,K-Y Warming Liquid Personal Lubricant For Warm...,9.99,19.98,2.0,2024-03-21,0.99,"[K-Y, Warming, Liquid, Personal, Lubricant, Wa..."
...,...,...,...,...,...,...,...
9995,Female Increase Orgasm Gel Vaginal Tightening ...,14.03,687.58,49.0,2023-11-03,0.00,"[Female, Increase, Orgasm, Gel, Vaginal, Tight..."
9996,K-Y Jelly Personal Lubricant Water Based Lube ...,18.80,37.60,2.0,2023-11-03,0.00,"[K-Y, Jelly, Personal, Lubricant, Water, Lube,..."
9997,Conceive Fertility Friendly Lubricant 8/pkConc...,19.99,179.91,9.0,2023-11-03,0.60,"[Conceive, Fertility, Friendly, Lubricant, Fer..."
9998,Hello Cake Tingle To Mingle Tingling Arousal G...,12.69,12.69,1.0,2023-11-03,0.00,"[Hello, Cake, Tingle, Mingle, Tingling, Arousa..."
9999,Pjur Original Concentrated Silicone - 3.4oz/10...,21.11,105.55,5.0,2023-11-03,0.00,"[Pjur, Original, Concentrated, Silicone, Perso..."

# Product_Research

In [11]:
filtered_df= data_df.loc[data_df['Avg_Sold_Price'] > 10]
filtered_df.head()

,Listing,Avg_Sold_Price,Total_Sales,Total_Sold,Date,Shipping,Title_Keywords
0,10oz Lubricant Semen Long Lasting Water Based ...,12.55,1029.34,82.0,2024-03-21,0.00,"[Lubricant, Semen, Long, Lasting, Water, Sex, ..."
2,New Pjur Original Bodyglide Silky Silicone Lub...,114.00,1026.00,9.0,2024-03-21,0.00,"[New, Pjur, Original, Bodyglide, Silky, Silico..."
7,Bad Dragon 🐉 Cum Lube Water Based Personal Lub...,22.71,37129.17,1635.0,2024-03-21,5.04,"[Bad, Dragon, 🐉, Cum, Lube, Water, Personal, L..."
8,6 Pack Pre-Seed Fertility Conception Friendly ...,108.07,18695.72,173.0,2024-03-21,0.00,"[Pack, Pre-Seed, Fertility, Conception, Friend..."
10,Pre-Seed Fertility-Friendly Personal Lubricant...,16.00,32.00,2.0,2024-03-21,0.00,"[Pre-Seed, Fertility-Friendly, Personal, Lubri..."

In [12]:
from collections import Counter
# Flatten the filtered lists
data_df_lists = filtered_df['Title_Keywords'].sum()

# Count the occurrences of each word
word_counts = Counter(data_df_lists)

# Find the most common words
most_common_words = word_counts.most_common()

In [13]:

def extract_phrases(title):
    tokens = title.split()  # Tokenize the title
    phrases = []
    for i in range(len(tokens)):
        for j in range(i + 1, min(i + 6, len(tokens) + 1)):  # Generate combinations of 2 to 5 words
            phrase = ' '.join(tokens[i:j])
            if len(phrase.split()) >= 2 and len(phrase.split()) <= 5:  # Check if phrase length is between 2 and 5
                phrases.append(phrase)
    return phrases

# Apply the function to the Titles column
phrases = filtered_df['Listing'].apply(extract_phrases).sum()

# Count the occurrences of each phrase
phrase_counts = Counter(phrases)

# Find the most common phrases
most_common_phrases = phrase_counts.most_common()

most_common_phrases_df = pd.DataFrame(most_common_phrases, columns=['Name', 'Count'])
most_common_phrases_df.head(25)

                              Name  Count
0               Personal Lubricant   4590
1                      Water Based   3297
2                   Based Personal   1383
3         Based Personal Lubricant   1129
4             Water Based Personal   1083
5                      Lubricant -    976
6   Water Based Personal Lubricant    878
7                         Sex Lube    713
8                  Based Lubricant    697
9                     Long Lasting    680
10           Water Based Lubricant    595
11                  Silicone Based    512
12                         for Men    509
13                        Lube for    450
14                  Lubricant Lube    446
15                   Personal Lube    443
16                   Lubricant for    424
17            Water-Based Personal    421
18                   Lube Personal    418
19                      Based Lube    404
20                  Lube Lubricant    379
21                   Sex Lubricant    356
22            Personal Lubricant -    346
23                           fl oz    345
24  Water-Based Personal Lubricant    343

In [14]:
# Filter the DataFrame
testing_df = filtered_df[filtered_df['Listing'].str.contains('Water Based')]
testing_df

,Listing,Avg_Sold_Price,Total_Sales,Total_Sold,Date,Shipping,Title_Keywords
0,10oz Lubricant Semen Long Lasting Water Based ...,12.55,1029.34,82.0,2024-03-21,0.00,"[Lubricant, Semen, Long, Lasting, Water, Sex, ..."
7,Bad Dragon 🐉 Cum Lube Water Based Personal Lub...,22.71,37129.17,1635.0,2024-03-21,5.04,"[Bad, Dragon, 🐉, Cum, Lube, Water, Personal, L..."
15,Hot Extra Warming F Cum Sauce Water Based Vagi...,21.95,351.20,16.0,2024-03-21,0.00,"[Hot, Extra, Warming, F, Cum, Sauce, Water, Va..."
16,Water Based Personal Lubricant 16 oz by Health...,15.95,200188.45,12551.0,2024-03-21,8.93,"[Water, Personal, Lubricant, oz, Healthy, Vibe..."
20,ID Glide Lube Water Based Natural Feel Persona...,17.19,105470.96,6134.0,2024-03-21,0.57,"[ID, Glide, Lube, Water, Natural, Feel, Person..."
...,...,...,...,...,...,...,...
9965,34oz Passion Natural Water Based Lubricant Eas...,15.99,31.98,2.0,2023-11-04,0.00,"[Passion, Natural, Water, Lubricant, Easy, Cle..."
9974,K-Y Ultragel Premium Water Based Personal Lubr...,66.24,132.48,2.0,2023-11-04,0.00,"[K-Y, Ultragel, Premium, Water, Personal, Lubr..."
9991,CVS Personal Lubricant Liquid Moisturizer Wat...,10.95,10.95,1.0,2023-11-03,0.00,"[CVS, Personal, Lubricant, Liquid, Moisturizer..."
9994,Lot Of 2-Wet Water Based Strawberry Flavored L...,14.99,14.99,1.0,2023-11-03,0.00,"[Lot, 2-Wet, Water, Strawberry, Flavored, Lubr..."
9996,K-Y Jelly Personal Lubricant Water Based Lube ...,18.80,37.60,2.0,2023-11-03,0.00,"[K-Y, Jelly, Personal, Lubricant, Water, Lube,..."

In [15]:
# Apply the function to the Titles column
phrases = testing_df['Listing'].apply(extract_phrases).sum()

# Count the occurrences of each phrase
phrase_counts = Counter(phrases)

# Find the most common phrases
most_common_phrases = phrase_counts.most_common()

In [26]:
most_common_phrases_df = pd.DataFrame(most_common_phrases, columns=['Name', 'Count'])
most_common_phrases_df.head(25)

                              Name  Count
0                      Water Based   3297
1               Personal Lubricant   1534
2                   Based Personal   1127
3             Water Based Personal   1083
4         Based Personal Lubricant    914
5   Water Based Personal Lubricant    878
6                  Based Lubricant    599
7            Water Based Lubricant    595
8                     Long Lasting    436
9                         Sex Lube    429
10                      Based Lube    340
11                Water Based Lube    322
12                     Lubricant -    302
13                 Lubricant Water    296
14           Lubricant Water Based    295
15                   Lubricant for    241
16                         for Men    214
17        Personal Lubricant Water    213
18  Personal Lubricant Water Based    213
19                   Lube Personal    201
20                        Lube for    194
21                   Premium Water    180
22             Premium Water Based    180
23                  Lubricant Long    175
24                  Lube Lubricant    163

In [29]:
# Filter the column containing the word "size"
# size_df = most_common_phrases_df[most_common_phrases_df['Name'].str.contains('Size')]

size_df = most_common_phrases_df

type_product = size_df['Name'].head(100).tolist()

In [31]:
dict_sales = {'Phrase': [], 'Avg_Sold_Price_mean': [], 'Avg_Sold_Price_25': [], 'Avg_Sold_Price_75': [], 'Total_Sold': [], 'Ship_Cost': []}

In [32]:
for phrase in type_product:
    # Filter rows where 'vitamin' or 'Vitamin' is in the list
    temp_df = testing_df[testing_df['Listing'].apply(lambda x: phrase in x)]

    mean = temp_df.describe()['Avg_Sold_Price'].tolist()[1]

    percent_25 = temp_df.describe()['Avg_Sold_Price'].tolist()[4]

    percent_75 = temp_df.describe()['Avg_Sold_Price'].tolist()[6]

    count = temp_df.describe()['Total_Sold'].tolist()[0]

    ship = temp_df.describe()['Shipping'].tolist()[5]
    
    dict_sales['Phrase'].append(phrase)
    dict_sales['Avg_Sold_Price_mean'].append(mean)
    dict_sales['Avg_Sold_Price_25'].append(percent_25)
    dict_sales['Avg_Sold_Price_75'].append(percent_75)
    dict_sales['Total_Sold'].append(count)
    dict_sales['Ship_Cost'].append(ship)
    
type_df = pd.DataFrame.from_dict(dict_sales)
type_df.head()

,Phrase,Avg_Sold_Price_mean,Avg_Sold_Price_25,Avg_Sold_Price_75,Total_Sold,Ship_Cost
0,Water Based,19.054484,12.600,22.000,1695.0,0.0
1,Personal Lubricant,19.467164,12.465,23.325,811.0,0.0
2,Based Personal,19.652261,12.980,23.270,566.0,0.0
3,Water Based Personal,19.661062,12.980,23.310,565.0,0.0
4,Based Personal Lubricant,20.002026,12.900,23.950,469.0,0.0

In [37]:
type_df.sort_values(by='Total_Sold', ascending=False).head(10)

,Phrase,Avg_Sold_Price_mean,Avg_Sold_Price_25,Avg_Sold_Price_75,Total_Sold,Ship_Cost
0,Water Based,19.054484,12.6000,22.0000,1695.0,0.0
1,Personal Lubricant,19.467164,12.4650,23.3250,811.0,0.0
2,Based Personal,19.652261,12.9800,23.2700,566.0,0.0
3,Water Based Personal,19.661062,12.9800,23.3100,565.0,0.0
4,Based Personal Lubricant,20.002026,12.9000,23.9500,469.0,0.0
5,Water Based Personal Lubricant,20.013397,12.9000,23.9500,468.0,0.0
6,Based Lubricant,18.634970,12.3275,21.6075,338.0,0.0
7,Water Based Lubricant,18.634970,12.3275,21.6075,338.0,0.0
9,Sex Lube,16.452518,10.9900,18.4450,278.0,0.0
8,Long Lasting,14.901833,10.9900,15.4800,251.0,0.0

In [36]:
type_df.sort_values(by='Avg_Sold_Price_mean', ascending=False).head(10)

,Phrase,Avg_Sold_Price_mean,Avg_Sold_Price_25,Avg_Sold_Price_75,Total_Sold,Ship_Cost
97,Personal Lubricant for Men and,29.306389,17.9900,34.99,36.0,0.0
95,Based Personal Lubricant for Men,28.823784,17.9900,34.99,37.0,0.0
70,Based Personal Lubricant for,28.475111,17.9900,34.99,45.0,0.0
71,Water Based Personal Lubricant for,28.475111,17.9900,34.99,45.0,0.0
82,Lubricant for Men and,28.287500,17.9900,34.99,40.0,0.0
76,for Men and,28.077674,17.9900,34.99,43.0,0.0
63,Personal Lubricant for Men,25.483125,16.1175,34.95,48.0,0.0
38,Men and,24.372131,15.9500,34.95,61.0,0.0
42,Lubricant for Men,24.143929,15.8200,34.95,56.0,0.0
33,Fl Oz,23.561899,14.5000,29.95,79.0,0.0

In [40]:
type_df.sort_values(by='Avg_Sold_Price_25', ascending=False)

,Phrase,Avg_Sold_Price_mean,Avg_Sold_Price_25,Avg_Sold_Price_75,Total_Sold,Ship_Cost
71,Water Based Personal Lubricant for,28.475111,17.9900,34.99,45.0,0.0
97,Personal Lubricant for Men and,29.306389,17.9900,34.99,36.0,0.0
70,Based Personal Lubricant for,28.475111,17.9900,34.99,45.0,0.0
82,Lubricant for Men and,28.287500,17.9900,34.99,40.0,0.0
95,Based Personal Lubricant for Men,28.823784,17.9900,34.99,37.0,0.0
...,...,...,...,...,...,...
85,Lubricant Water Based Long,13.074651,10.7800,12.96,43.0,0.0
56,Lasting Water,12.287800,10.5125,13.29,50.0,0.0
57,Lasting Water Based,12.287800,10.5125,13.29,50.0,0.0
79,Long Lasting Water Based,12.287800,10.5125,13.29,50.0,0.0
78,Long Lasting Water,12.287800,10.5125,13.29,50.0,0.0